Amadla: Amadla CLI
Amadla: {
    shape: image
    icon: https://raw.githubusercontent.com/SiteNetSoft/resources/master/images/sitenetsoft/amadla/amadla.png
}

Vault: {
    shape: image
    icon: https://raw.githubusercontent.com/SiteNetSoft/resources/master/images/onprem/security/vault.png
}

EnvFile: .env
EnvFile.shape: page

EnvVar: Environment Variable
EnvVar: {
    shape: image
    icon: https://raw.githubusercontent.com/SiteNetSoft/resources/master/images/programming/language/bash.png
}

AddSecretsToVars: Add Secrets To Vars
AddSecretsToVars.shape: rectangle
AddSecretsToVars: {
    style: {
        fill: "#DF2D2D"
        stroke: "#890B0B"
    }
}

Amadla -> EnvVar

EnvVar -> EnvFile: Not set
EnvVar -> AddSecretsToVars: Set

EnvFile -> Vault: Not set
EnvFile -> AddSecretsToVars: Set

Vault -> AddSecretsToVars: Set

RaiseNotFoundError: Raise Not Found Error
RaiseNotFoundError.shape: rectangle
Vault -> RaiseNotFoundError: Not set
