a1: {
  label: "Amadla"
  a3: {
    label: "Plugins"
  }
  x1: {
    label: "Hery"
    x2: {
      label: "Collections"
      x3: {
        label: "amadla"
        x5x2: {
          label: "Entity"
          a2: {
            label: "Templates"
            a2a1: {
              label: "Template"
            }
            a2a2: {
              label: "Template"
            }
          }
        }
        x5x3: {
          label: "Entity"
          a2: {
            label: "Templates"
            a2a1: {
              label: "Template"
            }
            a2a2: {
              label: "Template"
            }
          }
        }
      }
    }
  }
}
